### ISSUE TITLE
Locale de not found, falling back to en (warrning message)

### ISSUE THREAD

**Issue by Umair-Munir** [snipcart/snipcart-localization#45]
I have changed language from `en` to `de`. I have done all the configurations given in "Snipcart Documentation". But I am still getting warnings in logs whenever the page is reloaded.

<img width="650" alt="locale-warnings" src="https://cloud.githubusercontent.com/assets/8552862/24321841/98cc609e-1156-11e7-9d35-5638bcf077c3.png">
I have file "de.js" loaded in my application. But, It is still unable to find that file and try to search for `en` .  These are parts of my configurations
In HTML file

          <html lang="de">

in "de.js" file the code looks something like this

       Snipcart.execute('bind', 'app.ready', function () {
          Snipcart.execute('registerLocale', 'de', {
              first_name: "Vorname",
               last_name: "Nachname",
                ........................

How can I prevent this warnings?

**Comment by couellet** [comment]
You can add the following code snippet:

```js
<script>
document.addEventListener('snipcart.ready', function() {
Snipcart.DEBUG = false;
});
</script>
```

It will disable warning messages.

**Comment by Umair-Munir** [comment]
Is there any way to resolve these warning messages instead of hiding messages in console?
Whenever, I try to use locale of any language other than "en" these warnings messages are displayed in console.

**Comment by couellet** [comment]
I just merged the pull request you sent this week. Should be live in the next couple of minutes! It should solve the issue here.

**Comment by Umair-Munir** [comment]
Yes, almost all the warning messages have been removed. But I am still getting this warning message when I try to use locale other than `en`.

<img width="1183" alt="screen shot 2017-03-25 at 6 38 04 pm" src="https://cloud.githubusercontent.com/assets/8552862/24324647/86ef495c-118a-11e7-9d7a-d82012678a66.png">

**Comment by Mattrushka** [comment]
I am facing the same issue and error message as @Umair-Munir 
Are there any updates on this? It does not seem to affect any functionality but for people who are new to Snipcart the error message might be confusing. Maybe re-open the issue?

**Comment by datune** [comment]
@couellet Yup, same problem for me. Can we please fix this?

**Comment by benrom** [comment]
`Snipcart.DEBUG = false;` does not prevent the console from being filled with those language related logs.
